services:
  linux1:
    container_name: linux1
    build: ./linux1
    command: sh -c "service ssh start && service named start && rndc reload && tail -F /dev/null"
    ports:
      - 2201:22
    volumes:
      - ./linux1/named.conf.local:/etc/bind/named.conf.local
      - ./linux1/root.db:/etc/bind/root.db
    networks:
      mynet:
        ipv4_address: 192.168.1.11

  linux2:
    container_name: linux2
    build: ./linux2
    command: sh -c "service ssh start && named-checkconf && service named start && rndc reload && tail -F /dev/null"
    ports:
      - 2202:22
    volumes:
      - ./linux2/named.conf.local:/etc/bind/named.conf.local
      - ./linux2/mturtle.ru:/var/cache/mturtle.ru
      - ./linux2/xn--p1ai:/var/cache/xn--p1ai
    networks:
      mynet:
        ipv4_address: 192.168.1.12
  linux3:
    container_name: linux3
    build: ./linux3
    command: sh -c "service ssh start && service named start && rndc reload && tail -F /dev/null"
    volumes:
      - ./linux3/named.conf.options:/etc/bind/named.conf.options
      - ./linux3/root.hint:/usr/share/dns/root.hints
    ports:
      - 2203:22
    networks:
      mynet:
        ipv4_address: 192.168.1.14
    dns_search: mynet
  linux4:
    container_name: linux4
    build: ./linux4
    command: sh -c "service ssh start && tail -F /dev/null"
    ports:
      - 2204:22
    networks:
      mynet:
        ipv4_address: 192.168.1.15
    dns: 192.168.1.14 
  linux5:
    container_name: linux5
    build: ./linux5
    command: sh -c "service ssh start && named-checkconf && service named start && rndc reload && tail -F /dev/null"
    volumes:
      - ./linux5/named.conf.local:/etc/bind/named.conf.local
      - ./linux5/xn--k1ajfbd.xn--p1ai:/var/cache/xn--k1ajfbd.xn--p1ai
    ports:
      - 2205:22
    networks:
      mynet:
        ipv4_address: 192.168.1.13

networks:
  mynet:
    name: mynet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24